image: openjdk:8
vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.9.2:A7WIUV8jLUKzBJZUjM7zIg==
tasks:
- init: source ./gitpod_init.sh
- command: source ./gitpod_command.sh
